version: '3.3'

networks:
  my_network:
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  user:
    build:
      context: ./user           
      dockerfile: Dockerfile
    container_name: user
    networks:
      - my_network
    # environment:
      # - RABBITMQ_HOST=rabbitmq
      # - RABBITMQ_PORT=5672
      # - ABSOLUTE_DIR=/app/job_queries
      # - BATCH_SIZE=500
      # - DELAY_BETWEEN_BATCHES=0
      # - NUM_CHANNELS=3
      # - QUEUE_NAME=hello
    volumes:
      - /home/reiner/docker-experiments-tud/job_workload/job_queries:/app/job_queries
    depends_on: 
      - rabbitmq
  
  dispatcher:
    build:
      context: ./dispatcher           
      dockerfile: Dockerfile
    container_name: dispatcher
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - user
      - rabbitmq
    networks:
      - my_network

  collector:
    build:
      context: ./collector           
      dockerfile: Dockerfile
    container_name: collector
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
      - processor1
      - processor2
      - processor3
      - dispatcher
    networks:
      - my_network

  processor1:
    build:
      context: ./processor1           
      dockerfile: Dockerfile
    container_name: processor1
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
    networks:
      - my_network

  processor2:
    build:
      context: ./processor2           
      dockerfile: Dockerfile
    container_name: processor2
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
    networks:
      - my_network

  processor3:
    build:
      context: ./processor3           
      dockerfile: Dockerfile
    container_name: processor3
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
    networks:
      - my_network

  # postgresql: 
  #   external: true